// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZTpZR7nkZACFb6jWJAwLHBPYaiKucjnE',
    appId: '1:317938665213:web:a52ce57d221fccce642094',
    messagingSenderId: '317938665213',
    projectId: 'todolist-94119',
    authDomain: 'todolist-94119.firebaseapp.com',
    storageBucket: 'todolist-94119.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzK0dIzCogi3y9gVbBoriKwoz_wckaow',
    appId: '1:317938665213:android:660e9086ba372ee7642094',
    messagingSenderId: '317938665213',
    projectId: 'todolist-94119',
    storageBucket: 'todolist-94119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5nLlkQq8JhaStU6pbU5Dg0jX-e7o9Ne0',
    appId: '1:317938665213:ios:d7e71ccdc5c90067642094',
    messagingSenderId: '317938665213',
    projectId: 'todolist-94119',
    storageBucket: 'todolist-94119.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );
}
